Check auto-deploy with docker-buildx #5

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -65,7 +65,7 @@ jobs:
             
             # Логинимся в GHCR на NAS
             echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-            
+
             # Скачиваем новый образ
             docker pull ghcr.io/${{ github.repository_owner }}/jeo-pardy-app:latest
             
@@ -84,9 +84,9 @@ jobs:
       - name: Health check
         run: |
           sleep 5
-            if curl -f http://localhost:8082; then
-              echo "✅ Deployment successful!"
-            else
-              echo "❌ Health check failed!"
-              exit 1
-            fi
+          if curl -f http://localhost:8082; then
+            echo "✅ Deployment successful!"
+          else
+            echo "❌ Health check failed!"
+            exit 1
+          fi
